### ISSUE TITLE
First release TODO

### ISSUE THREAD

**Issue by knuxify** [knuxify/eartag#1]
- [X] Album cover support (e8281b3b0e9ce8c8f67256aaeb4e854ec180f7e4)
    - [X] Some more changes to make it look nicer (ae1a7084dcc4c7b586cee5b3d576160f305ab908)
 - [X] User-friendly error messages (cb16dc68043b94cc2afd21b60d7c03e4171df894)
 - [X] Editable labels for title and description (e01eb9bfd495a8e96d61906799345e09d3acf54a)
     - [X] Add placeholder labels (83d7fd6ff227ec11941f5cc055f32c8c827912ae)
 - [X] Add "release year" column (3714daaeca7a8a3ebbacf1b374e79f3fa0b58d07)
 - [X] Figure out why "comment" is broken (fixed by switching to taglib)
 - [X] Implement drag-and-drop (454da7841baf6641035b3ede1ea5a2b2847df965)
 - [X] Warn about unsaved changes on exit (20b94f4e3b13c1471905e30f357c7da0b67c78ba)
 - [X] Allow running from command-line (da9b3aecf4b97923ef4b2a273f4d4af12c29ee79)
 - [X] Write README, CONTRIBUTING etc. (d139bea5595441acbf6ce2a7603b2b60160e71aa)
 - [X] Assign as opener for audio files (a10c59450cee99dc91fb7263aa563a6b198e5dd9)
 - [X] Add track number row (b96eab06248b44f6552d57b0d2c4f99ee38563c7)
 - [X] Add open, save keybind (Ctrl+O, Ctrl+S) (df1a2b8f050f8d201a711655c25c2cdcf57071b6)
 - [X] Add error detection/messages on saving (986bf160150832fdc39994765b5498569d55ee6a)
 - [X] Move filetype detection into single function, add missing types (see .desktop file) (a686def925a54c855d3caa6905ef7e5af952463b)
 - ~~Add ability to remove tags~~ apparently eyed3 doesn't have a nice API for this...
 
...also I'm considering slipping support for multiple files into the first release, since it's really nice to have.

## Stretch goals

 - Musicbrainz support
 - Support for opening multiple files at once (edits tags in all files)
 - Preferences menu
