### ISSUE TITLE
GNOME Circle inclusion

### ISSUE THREAD

**Issue by knuxify** [knuxify/eartag#41]
Small tasks to do before I apply for GNOME Circle inclusion:

- [X] Add .doap file (0968336f32be57ee5b90ea7a505cb9efa6c3c292)
- [X] Adapt to libadwaita 1.2 (#6)
- [ ] Add tests for file handling (#28) - need to make 100% sure we're not doing any damage to users' files
- [ ] Change the way error messages are display (using dialogs for this is against HIG)
